# Generated by Django 5.2.7 on 2026-02-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='soundcloud_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='spotify_id',
        ),
    ]
